# bpytop template for wpgtk
# by improvisedexplosivedevice

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient


# TEXT
theme[main_fg]="#e5e9f0"          # Main text color
theme[title]="#e5e9f0"            # Title color for boxes
theme[hi_fg]="#5E81AC"            # Higlight color for keyboard shortcuts
theme[inactive_fg]="#4C566A"       # Color of inactive/disabled text
theme[graph_text]="#A3BE8C"       # Color of text appearing on top of graphs, i.e uptime and current network graph scaling


# OTHER
theme[main_bg]="#2E3440"           # Main background, empty for terminal default, need to be empty if you want transparent background
theme[selected_bg]="#4C566A"       # Background color of selected item in processes box
theme[selected_fg]="#E5E9F0"       # Foreground color of selected item in processes box
theme[proc_misc]="#A3BE8C"        # Misc colors for processes box including mini cpu graphs, details memory graph and details status text


# OUTLINES
theme[cpu_box]="#5E81AC"           # Cpu box outline color
theme[mem_box]="#88C0D0"           # Memory/disks box outline color
theme[net_box]="#5E81AC"           # Net up/down box outline color
theme[proc_box]="#88C0D0"          # Processes box outline color
theme[div_line]="#88C0D0"          # Box divider line and small boxes line color


# METERS
theme[meter_bg]="#4C566A"          # Background color of the percentage meters
theme[used_start]="#A3BE8C"        # Mem/Disk used meter
theme[used_mid]=""
theme[used_end]="#A3BE8C"
theme[available_start]="#D08770"   # Mem/Disk available meter
theme[available_mid]=""
theme[available_end]="#D08770"
theme[cached_start]="#A3BE8C"      # Mem/Disk cached meter
theme[cached_mid]=""
theme[cached_end]="#A3BE8C"
theme[free_start]="#D08770"        # Mem/Disk free meter
theme[free_mid]=""
theme[free_end]="#D08770"


# GRAPHS
theme[temp_start]="#367bf0"         # Temperature graph colors
theme[temp_mid]="#b8174c"
theme[temp_end]="#d41919"
theme[cpu_start]="#5E81AC"        # CPU graph colors
theme[cpu_mid]="#BF616A"
theme[cpu_end]="#88C0D0"
theme[download_start]="#A3BE8C"    # Download graph colors
theme[download_mid]="#88C0D0"
theme[download_end]="#88C0D0"  
theme[upload_start]="#BF616A"     # Upload graph colors
theme[upload_mid]="#BF616A"
theme[upload_end]="#D08770"
theme[process_start]="#A3BE8C"    # Process box color gradient for threads, mem and cpu usage
theme[process_mid]="#D08770"
theme[process_end]="#EBCB8B"
